#!/bin/zsh
BASE=/Users/$(whoami)/Documents/autosign
FILE=$(basename $1)
SIGN=$1

scp "$1" $(whoami)@mariko:"$BASE/unsigned"
ssh $(whoami)@mariko "while [ ! -f "$BASE/signed/$FILE" ]; do sleep 1; done; sleep 2"
mv "$1" "${1}_"
scp $(whoami)@mariko:"$BASE/signed/$FILE" "$SIGN"

